# Generated by Django 2.0.13 on 2019-08-28 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='상품설명'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image/', verbose_name='대표이미지'),
            preserve_default=False,
        ),
    ]
