# Generated by Django 2.0.13 on 2019-08-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20190828_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(default=10000, verbose_name='상품가격'),
            preserve_default=False,
        ),
    ]
